spring:
  ai:
    mcp:
      server:
        name: date-server
        version: 1.0.0
        type: SYNC
        instructions: "提供获取不同时区的当前时间，并按照北京时间进行展示"
        sse-message-endpoint: /mcp/messages
        sse-endpoint: /sse
        capabilities:
          tool: true # 是否支持工具
          resource: true # 是否支持资源
          prompt: true # 是否支持提示词
          completion: true # 是否支持补全

qyplm:
  base-url: http://139.159.221.11:9002
  pages:
    - '{"我的PLM":"[点击打开](menu=我的PLM)"}'
    - '{"高级搜索":"[点击打开](menu=高级搜索)"}'
    - '{"AI计价-计价参数":"[点击打开](menu=计价参数)"}'
    - '{"AI计价-计价产品":"[点击打开](menu=计价产品)"}'
    - '{"AI计价-数据维护":"[点击打开](menu=数据维护)"}'
    - '{"AI计价-成本分析":"[点击打开](menu=成本分析)"}'
    - '{"需求管理-需求解读":"[点击打开](menu=需求解读)"}'
    - '{"需求管理-需求库":"[点击打开](menu=需求库)"}'
    - '{"配置管理-配置任务":"[点击打开](menu=配置任务)"}'
    - '{"BOM视图/结构管理器":"[点击打开](menu=BOM视图)"}'

# 修改日志级别
logging:
  level:
    org.springframework.ai.chat.client.advisor.SimpleLoggerAdvisor: debug
    io.modelcontextprotocol.server.transport.WebMvcSseServerTransportProvider: debug